// TODO Legal review — first draft prepared by product + engineering teams based on
// PRD-v4 §10 business rules and the company entity record. Must be reviewed by a
// Hong Kong qualified solicitor before public release; final clause numbering,
// jurisdiction wording and breach-of-contract details follow the lawyer's signed copy.
export default {
  legal: {
    terms: {
      title: 'Mandarly Terms of Service',
      seoTitle: 'Mandarly Terms of Service · User Agreement',
      seoDescription: 'Terms of Service for Mandarly online 1-on-1 Mandarin Chinese tutoring platform. Covers accounts, course packages, refunds, teacher earnings, referral codes, intellectual property and dispute resolution. Operated by MANDARLY TECHNOLOGY LIMITED, governed by the laws of Hong Kong SAR.',
      seoKeywords: 'Mandarly terms of service, user agreement, online Mandarin tutoring agreement, MANDARLY TECHNOLOGY LIMITED',
      lastUpdated: 'Last updated: 2026-05-09',
      effectiveDate: 'Effective date: 2026-05-09',
      backToHome: 'Back to home',
      companyName: 'MANDARLY TECHNOLOGY LIMITED',
      companyNameZh: '曼德勵科技有限公司',
      companyNameEn: 'MANDARLY TECHNOLOGY LIMITED',
      companyAddress: 'RM 131, 1/F, 143 Wai Yip Street, Kwun Tong, Hong Kong',
      contactEmail: 'support{\'@\'}mandarly.com',
      sections: {
        intro: {
          heading: '1. General Provisions',
          body: 'Welcome to Mandarly (hereinafter "the Platform" or "we"). These Terms of Service (the "Agreement") are entered into between MANDARLY TECHNOLOGY LIMITED (Chinese name: 曼德勵科技有限公司; a company incorporated in the Hong Kong Special Administrative Region of the People\'s Republic of China; hereinafter the "Company") and you (the "User") with respect to your use of the online 1-on-1 Mandarin Chinese tutoring services and related features made available through the Platform. The Platform is a commercial Mandarin learning marketplace for learners in Hong Kong and overseas, serving both students and teachers. Please read this Agreement carefully before using the Platform, in particular the clauses on payment, refunds, limitation of liability and dispute resolution that are highlighted in bold or underlined. By completing registration, signing in, paying or otherwise using any service on the Platform, you confirm that you have read, understood and agreed to be bound by all terms herein. If you do not agree with any clause, please stop using the Platform.'
        },
        accountRules: {
          heading: '2. Account & Registration',
          body: '2.1 Eligibility: You must be a natural person with full civil capacity and at least 13 years of age. Users under 18 must register and use the Platform with the consent and supervision of a parent or legal guardian, who shall bear full responsibility for the User\'s conduct on the Platform.\n2.2 Sign-up Methods: The Platform supports four sign-up and login methods: email, mobile phone number, Google and Apple. A natural person may bind multiple login methods to the same account, but must not register multiple accounts to engage in fraudulent ordering, reward farming, fake reviews or similar misconduct.\n2.3 Accurate Information: You shall provide true, accurate and complete registration information (including email, mobile, name, etc.) and update such information in a timely manner if it changes. Account control measures, order failures or refund disputes caused by false information are at your own risk.\n2.4 Account Security: You shall keep your password and login credentials secure and shall not lend, transfer or share your account with any third party. All activities under your account (including ordering, payment, attending lessons and submitting withdrawal requests) shall be deemed performed by you. The Company is not liable for losses caused by your disclosure of credentials. If you suspect unauthorised access, please contact ' + 'support{\'@\'}mandarly.com immediately.\n2.5 Referral Code: Upon successful registration, the system will automatically generate a unique referral code that you may share with others to invite new users and earn rewards. Detailed rules are set out in Section 7.'
        },
        serviceContent: {
          heading: '3. Service Scope',
          body: '3.1 Platform Positioning: Mandarly provides a Mandarin Chinese (Putonghua) 1-on-1 online speaking tutoring matching service, covering daily conversation, business Chinese, HSK, children\'s Chinese, level placement testing and personalised study plans.\n3.2 Lesson Format: Lessons are delivered through an embedded in-browser video classroom (Tencent Cloud LCIC). Each lesson lasts a fixed 30 minutes. Students must reserve a teacher\'s available slot in advance and complete payment before joining the classroom.\n3.3 Package Purchase: Students obtain lesson credits by purchasing course packages. Each package specifies the weekly quota, total credits, validity period and price as displayed on the order page at the time of purchase. A package becomes effective and starts counting its validity from the date of successful payment. Unused credits remaining after the validity period generally are not refundable; the Company may exceptionally extend a package at its discretion.\n3.4 Teacher Matching: Students may select a teacher by completing the level placement test or browsing teacher profiles. The Company verifies teacher credentials but does not warrant that any particular teacher\'s style or teaching outcome will fully meet a student\'s expectation; specific lesson content is to be agreed between teacher and student before each session.\n3.5 Free Trials: Newly registered users may be entitled to a complimentary trial lesson, subject to the prevailing campaign rules announced on the Platform. Free trial lessons are not counted in the refund base.\n3.6 Service Availability: The Platform is an online service and may experience brief unavailability due to network conditions, third-party services (LCIC, Stripe, email/SMS providers) or force majeure events. The Company will use reasonable efforts to restore the service but shall not be liable for damages arising from such short-term interruptions.'
        },
        userObligations: {
          heading: '4. User Obligations & Code of Conduct',
          body: '4.1 Lawful Use: You shall not use the Platform for any activity that violates the laws of Hong Kong SAR or the laws applicable to your location, including but not limited to fraud, money laundering, pornography, gambling, distributing prohibited content or infringing the intellectual property or lawful rights of others.\n4.2 Civil Conduct: During lessons, Users shall maintain basic etiquette and shall not insult, harass, discriminate against or sexualise teachers or other Users. Lesson recordings (if any) are used solely for quality control and dispute resolution and will not be made public.\n4.3 Genuine Reviews: Students may rate teachers after a lesson. Reviews shall be objective and truthful; malicious defamation, fabrication or paid reviews are prohibited.\n4.4 No Abuse: You shall not use technical means to interfere with the Platform, including but not limited to scraping, fraudulent ordering, fake bookings, bypassing payment, or batch-creating accounts via automation.\n4.5 Teacher-Specific Obligations: As a teacher User, you shall further warrant that the qualification documents you submit (degrees, teaching certificates, related credentials) are authentic and valid. You shall conduct lessons on time. The Company may, in accordance with its rules, deduct lesson income and compensate students if you are late, absent, or end lessons early without justification.\n4.6 Breach Handling: If you breach any provision of this Section, the Company may issue warnings, restrict features, suspend or terminate your account, deduct teacher income, withhold remaining package balance and, where serious, report the matter to the relevant law-enforcement authorities.'
        },
        paymentRefund: {
          heading: '5. Payment & Refund',
          body: '5.1 Payment Channel: The Platform uses Stripe as its unified online payment channel, supporting Visa, Mastercard, WeChat Pay, Alipay, Apple Pay and other mainstream methods, and settlements in HKD, USD, CNY and other currencies as displayed on the order page.\n5.2 Package Pricing: Package prices are those displayed at the time of order. The Company may adjust prices from time to time, but successfully paid orders are not affected by subsequent price changes.\n5.3 Cancellation & Refund Rules (refer to PRD §10 items 1, 3, 4, 5):\n  · If a purchased package has not been consumed at all, the Student may request a full refund within the package validity period; the Company will normally refund through the original payment channel within 7–15 business days after approval.\n  · For partially consumed packages, the refund is calculated pro rata on the unused credits (remaining credits ÷ total credits × amount paid). Used credits are not refundable.\n  · For a single booked lesson, if the Student cancels at least 24 hours before the scheduled time, the credit is fully returned to the package balance; cancellations within 24 hours of the scheduled time are non-refundable and the credit is forfeited.\n  · If a lesson cannot proceed due to teacher cancellation, no-show, or technical failure attributable to the teacher or the Platform, the credit is fully returned, and the Company will assist with a full refund of the entire order if requested.\n5.4 Refund Method: Refunds are returned via the original payment channel. If the original channel is unavailable due to third-party policy, the Company may discuss an alternative reasonable method with you.\n5.5 Chargebacks: You shall not obtain improper benefits through fraudulent transactions or abusive chargebacks. If the Platform verifies abusive chargeback behaviour, the Company may recover the corresponding amount and freeze or terminate your account.'
        },
        teacherIncome: {
          heading: '6. Teacher Earnings & Withdrawal (Teacher Users Only)',
          body: '6.1 Lesson Rate: The teacher lesson rate is a unified rate, with the specific amount determined by separate agreement between the teacher and the Company or by back-office configuration. Free trial lessons do not generate teacher income (PRD §10 item 3).\n6.2 Settlement: After each completed lesson, the system computes the teacher\'s share according to the platform commission rules and marks it as "Pending Settlement". On the 7th calendar day after lesson completion (T+7), the freeze period ends and the amount is automatically transferred to "Available Balance" (PRD §10 item 7).\n6.3 Refund Deduction: If the lesson is later refunded to the Student following an approved refund request, the corresponding teacher income shall be deducted from the teacher\'s balance. If the available balance is insufficient, the deficit may be offset against future income.\n6.4 Withdrawal Threshold: A teacher may submit a withdrawal request once the available balance reaches USD 100 (or equivalent in another currency). Transaction fees are borne by the teacher (PRD §10 item 6).\n6.5 Withdrawal Process: The teacher fills in payee information (bank account, PayPal, or another method recognised by the Company) under "My Earnings → Request Withdrawal". An administrator will review the request. Once approved, the Company will transfer offline using the provided payee details and mark the request as "Paid". If rejected, the balance will be unfrozen and may be requested again.\n6.6 Tax: Teachers act as independent contractors and are responsible for declaring and paying any taxes due on their earnings to the relevant tax authority of their tax residence. The Company does not withhold individual income tax.'
        },
        referral: {
          heading: '7. Referral Code',
          body: '7.1 Referral Reward Rules (refer to PRD §10 item 8 / §U4):\n  · Each registered User receives a unique referral code that may be shared with others.\n  · A new User who completes their first package purchase using a referral code receives a discount of CNY 30 (or equivalent in another currency, as displayed on the order page).\n  · The referrer receives one (1) free lesson credit for each successful first-purchase referral, credited directly to the referrer\'s account.\n7.2 Anti-Abuse: A natural person must not exploit the referral programme through multiple accounts, fake identities or impersonation. Where such behaviour is detected, the Company may revoke rewards, deduct corresponding balances, recover funds and terminate the offending accounts.\n7.3 Adjustment: The Company reserves the right to adjust referral reward amounts, eligibility conditions and validity from time to time, and will publish such changes via Platform announcements or in-app notices.'
        },
        intellectualProperty: {
          heading: '8. Intellectual Property',
          body: '8.1 Platform Assets: The Platform name (Mandarly / 曼德勵), logo, UI design, brand colours, copy, graphics, source code, courseware and operational materials, together with the related copyright, trademark, patent and other intellectual property rights, belong to the Company or the relevant rights holders, and are protected by the laws of Hong Kong SAR and other applicable jurisdictions. No copying, modification, distribution, commercial use or reverse engineering is permitted without prior written authorisation.\n8.2 Teacher-Created Content: The original courseware, lesson plans and teaching content created by a teacher remain owned by the teacher. The teacher hereby grants the Company a non-exclusive, sublicensable, worldwide, royalty-free licence to use such content for Platform operation, promotion and quality control.\n8.3 User-Generated Content: The copyright in reviews, comments, Q&A and similar content posted by Users on the Platform belongs to the User, who hereby grants the Company a worldwide, royalty-free, perpetual, irrevocable, sublicensable licence to use such content for display, operation, promotion and quality improvement.\n8.4 Third-Party Content: Third-party trademarks, fonts and images that may appear on the Platform belong to their respective rights holders; the Company has obtained the necessary licences or relies on fair use principles.'
        },
        liabilityLimit: {
          heading: '9. Limitation of Liability',
          body: '9.1 As-Is Service: The Platform is provided on an "as is" and "as available" basis. To the extent permitted by applicable mandatory law, the Company makes no express or implied warranty regarding the continuity or error-free operation of the service or any specific learning outcome (such as reaching a particular HSK level after a specific number of lessons).\n9.2 Indirect Damages: To the maximum extent permitted by applicable law, the Company shall not be liable for any indirect, incidental, special or punitive losses (such as lost employment opportunities, exam scores or commercial benefits) arising from your use of the Platform.\n9.3 Cap on Liability: In any event, the Company\'s aggregate liability for matters under this Agreement shall not exceed the total amount actually paid by you to the Company through the Platform in the 12 months preceding the dispute event.\n9.4 Force Majeure: The Company is not liable for any service interruption or loss caused by force majeure events, including war, civil unrest, natural disasters, governmental acts, changes in laws or regulations, or large-scale failure of power, network or third-party services, but will use reasonable efforts to mitigate your loss.\n9.5 Third-Party Services: The Platform integrates third-party services such as Stripe (payment), Tencent Cloud LCIC (video), Google / Apple (federated login), Alibaba Cloud Email and Tencent Cloud SMS. Failures, policy changes or compliance risks of those third parties are governed by their respective terms of service.'
        },
        termination: {
          heading: '10. Termination',
          body: '10.1 Voluntary Account Closure: You may close your account at any time through the in-app "Account & Security" entry or by contacting customer support. Before closing, please ensure all packages are used up, all orders settled, and all teacher available balance withdrawn. The Company will not provide cash refunds for unused balance, unwithdrawn amounts or unused credits after closure, although duly filed refund requests will continue to be processed.\n10.2 Termination by Platform: The Company may unilaterally suspend or terminate your service and close your account in any of the following circumstances:\n  · You materially breach any term of this Agreement;\n  · You provide false information, impersonate others, or engage in fraud, money laundering or fraudulent ordering;\n  · A judicial or administrative authority requires it, or changes in laws or regulations make continued service impossible;\n  · The Platform is wound down in its entirety.\n10.3 Effect of Termination: Upon termination, you no longer have the right to use the Platform, but the provisions in this Agreement on intellectual property, limitation of liability, dispute resolution and final right of interpretation shall survive. The handling of personal data is governed by the Mandarly Privacy Policy.'
        },
        governingLaw: {
          heading: '11. Governing Law & Dispute Resolution',
          body: '11.1 This Agreement shall be governed by and construed in accordance with the laws of the Hong Kong Special Administrative Region of the People\'s Republic of China.\n11.2 Any dispute arising out of or in connection with this Agreement or the Platform shall first be resolved through friendly negotiation. If negotiation fails, either party may:\n  · bring proceedings in a court of competent jurisdiction in Hong Kong SAR; or\n  · refer the dispute to the Hong Kong International Arbitration Centre (HKIAC) for arbitration in accordance with the HKIAC Administered Arbitration Rules in force at the time of submission. The seat of arbitration shall be Hong Kong, and the language of arbitration shall be Chinese (or English if the parties so agree in writing).\n11.3 The arbitral award shall be final and binding upon both parties.'
        },
        changes: {
          heading: '12. Amendments',
          body: '12.1 The Company may revise this Agreement from time to time in light of changes in laws, operational strategy or service features. Revised versions will be published via Platform announcements, in-app notices or registered email at least 7 days before they take effect; for material changes affecting your rights (e.g., fees, refunds, liability limits), the Company will use a more prominent notification method.\n12.2 If you continue to use the Platform after the notice period expires, you are deemed to have accepted the revised Agreement. If you do not accept the revisions, you should stop using the Platform during the notice period and close your account in accordance with Section 10.'
        },
        finalInterpretation: {
          heading: '13. Final Right of Interpretation',
          body: 'The Platform is operated by MANDARLY TECHNOLOGY LIMITED (Chinese: 曼德勵科技有限公司), which reserves the final right of interpretation over the Platform\'s rules, campaigns and marketing materials.'
        },
        contact: {
          heading: '14. Contact Us',
          body: 'If you have any questions, complaints or suggestions regarding this Agreement, the Platform or your account, please contact us via the following:\n\nCompany name (English): MANDARLY TECHNOLOGY LIMITED\nCompany name (Chinese): 曼德勵科技有限公司\nRegistered address: RM 131, 1/F, 143 Wai Yip Street, Kwun Tong, Hong Kong\nContact email: support{\'@\'}mandarly.com\n\nWe will reply as soon as reasonably practicable after receiving your enquiry.'
        }
      }
    }
  }
}
